"""The attention monitor: an observer that tells the driver when driving stops looking ordinary.

Division of labour:

* The n-gram model decides *when*. Each completed event is scored by its
  surprisal given the recent events. An event is flagged if its surprisal is at
  or above the calibrated threshold, or if its type never occurred in nominal
  training data at all (see :meth:`AttentionModel.flags`).
* Fixed templates decide *what to say*. The message is built from the measured
  features of the flagged window (time-to-collision, braking, lane offset,
  mode), never generated by the model, so every word shown to the driver is
  traceable to a number the system actually measured.

Delivery rules keep the monitor in a supporting role:

* It stays quiet while the safety supervisor has an alert up. The supervisor's
  deterministic alerts (EMERGENCY BRAKING, TAKE CONTROL) always take precedence,
  and a second message on top of them would compete for the same attention.
* It only speaks while the system has full control. When the driver is already
  steering or driving, "stay alert" is noise.
* After an advisory it holds off for ``model.holdoff`` seconds, to limit alert
  fatigue, unless the new reason is more severe than the last one delivered:
  an escalation is never held back.

Every flag is kept in :attr:`AttentionMonitor.flags` whether or not it was
delivered, and why not, so a post-drive review sees everything the model found.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from ..observe import Advisory, Snapshot
from .events import Event, Features, Windower
from .model import AttentionModel

#: Every message the monitor can produce is one of these, filled with numbers,
#: listed from most to least severe. Kept as data so tests can check that
#: nothing outside this set is ever shown and that escalation follows this order.
TEMPLATES: dict[str, str] = {
    "aeb": "emergency braking in progress",
    "fault": "system fault",
    "stale": "perception data is stale",
    "closing": "closing on the vehicle ahead, time to collision {ttc:.1f} s",
    "braking": "hard braking at {accel:.1f} m/s²",
    "lane": "{lateral:.2f} m from lane center",
    "driver_steering": "driver steering",
    "driver": "driver in control",
    "unusual": "unusual sequence of driving events",
}
SEVERITY: dict[str, int] = {key: len(TEMPLATES) - i for i, key in enumerate(TEMPLATES)}
PREFIX = "Stay alert: "


def reason_for(f: Features) -> tuple[str, str]:
    """The most safety-relevant measured fact about a flagged window, as (key, text)."""

    if f.aeb:
        return "aeb", TEMPLATES["aeb"]
    if f.mode == "fault":
        return "fault", TEMPLATES["fault"]
    if f.stale:
        return "stale", TEMPLATES["stale"]
    if f.ttc_band is not None and f.ttc_band <= 1:
        return "closing", TEMPLATES["closing"].format(ttc=f.min_ttc)
    if f.accel_band == 0:
        return "braking", TEMPLATES["braking"].format(accel=f.min_accel)
    if f.lateral_band is not None and f.max_lateral is not None and f.lateral_band >= 2:
        return "lane", TEMPLATES["lane"].format(lateral=f.max_lateral)
    if f.mode == "lat_override":
        return "driver_steering", TEMPLATES["driver_steering"]
    if f.mode == "off":
        return "driver", TEMPLATES["driver"]
    return "unusual", TEMPLATES["unusual"]


@dataclass(frozen=True)
class Flag:
    t: float                  # s, when the flag was raised (end of the window + at most one step)
    event: Event
    surprisal_bits: float
    novel: bool               # event type never seen in nominal training data
    reason: str               # key into TEMPLATES
    message: str
    delivered: bool
    withheld_because: str | None


class AttentionMonitor:
    """Implements :class:`autodrive.observe.Observer`."""

    def __init__(self, model: AttentionModel):
        self.model = model
        self.flags: list[Flag] = []
        self.scores: list[tuple[Event, float]] = []   # every event and its surprisal
        self._windower = Windower(model.spec)
        self._history: list[str] = []
        self._last_delivered = -math.inf
        self._last_severity = 0

    def observe(self, snapshot: Snapshot) -> Advisory | None:
        event = self._windower.push(snapshot)
        if event is None:
            return None
        bits = self.model.lm.surprisal(self._history, event.token)
        self._history.append(event.token)
        del self._history[:-max(1, self.model.lm.order - 1)]
        self.scores.append((event, bits))
        if not self.model.flags(event.token, bits):
            return None

        key, text = reason_for(event.features)
        message = PREFIX + text + "."
        withheld = self._withhold(snapshot, SEVERITY[key])
        novel = event.token not in self.model.lm.vocabulary
        self.flags.append(Flag(snapshot.t, event, bits, novel, key, message, withheld is None, withheld))
        if withheld is not None:
            return None
        self._last_delivered, self._last_severity = snapshot.t, SEVERITY[key]
        return Advisory(snapshot.t, message, bits)

    def _withhold(self, snapshot: Snapshot, severity: int) -> str | None:
        if snapshot.alert is not None:
            return "safety alert active"
        if snapshot.mode == "lat_override":
            return "driver already steering"
        if snapshot.mode != "engaged":
            return "system not engaged"
        recent = snapshot.t - self._last_delivered < self.model.holdoff
        if recent and severity <= self._last_severity:   # an escalation is never held back
            return "hold-off"
        return None
